port: 3333

theme: 14 # bootswatch.themes[n]

authors:
    - Joshua Mervine
    - Justin Dorfman

description: Bootstrap CDN

favicon: "/favicon.ico"

google_analytics:
    account_id: UA-32253110-1
    domain_name: bootstrapcdn.com

####
# Turn stats on or off.
# - Use 'stub' to develop against test stub.
extras: true

####
# Note: stylesheets and javascript will be loaded
# in the order they are specified.
stylesheets:
    - "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
    - "/stylesheets/style.css"

javascript:
    # scripts specified in the before group will be loaded
    # as blocking scripts inside the head tag
    #before:
    #
    # scripts specified in the after group will be loaded
    # as blocking scripts at the bottom of the page
    after:
        - "//code.jquery.com/jquery-1.11.2.min.js"
        - "//maxcdn.bootstrapcdn.com/bootstrap/SWATCH_VERSION/js/bootstrap.min.js"

####
# TODO: Perhaps move to a database (redis or mongo),
# or to its own configuration file.
#
# In the configs below, SWATCH_NAME will be replaced with
# the corresponding theme. SWATCH_VERSION will be replaced with
# the version specified.
bootswatch:
    version: "3.3.4"
    link: "http://bootswatch.com/SWATCH_NAME/"
    image: "http://bootswatch.com/SWATCH_NAME/thumbnail.png"
    bootstrap: "//maxcdn.bootstrapcdn.com/bootswatch/SWATCH_VERSION/SWATCH_NAME/bootstrap.min.css"
    themes:
        - cerulean  # 0
        - cosmo     # 1
        - cyborg    # 2
        - darkly    # 3
        - flatly    # 4
        - journal   # 5
        - lumen     # 6
        - paper     # 7
        - readable  # 8
        - sandstone # 9
        - simplex   # 10
        - slate     # 11
        - spacelab  # 12
        - superhero # 13
        - united    # 14
        - yeti      # 15

####
# TODO: Perhaps move to a database (redis or mongo),
# or to its own configuration file.
bootlint:
    - version: "0.12.0"
      latest: true
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.12.0/bootlint.min.js"

    - version: "0.11.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.11.0/bootlint.min.js"

    - version: "0.10.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.10.0/bootlint.min.js"

    - version: "0.9.1"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.9.1/bootlint.min.js"

    - version: "0.9.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.9.0/bootlint.min.js"

    - version: "0.8.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.8.0/bootlint.min.js"

    - version: "0.7.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.7.0/bootlint.min.js"

    - version: "0.6.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.6.0/bootlint.min.js"

    - version: "0.5.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.5.0/bootlint.min.js"

    - version: "0.4.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.4.0/bootlint.min.js"

    - version: "0.3.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.3.0/bootlint.min.js"

    - version: "0.2.0"
      javascript:  "//maxcdn.bootstrapcdn.com/bootlint/0.2.0/bootlint.min.js"

bootstrap:
    - version: "3.3.4"
      latest: true
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"

    - version: "3.3.2"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"

    - version: "3.3.1"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"

    - version: "3.3.0"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"

    - version: "3.2.0"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"

    - version: "3.1.1"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"

    - version: "3.1.0"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"

    - version: "3.0.3"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"

    - version: "3.0.2"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"

    - version: "3.0.1"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"

    - version: "3.0.0"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"

    - version: "3.0.0-noicons"
      css_complete: "//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"

    - version: "2.3.2"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css"
      css_no_icons: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"

    - version: "2.3.2-noicons"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"

    - version: "2.3.1"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"

    - version: "2.3.0"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"

    - version: "2.2.2"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css"
      css_no_icons: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap.min.nr.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"

    - version: "2.2.2-noresponsible"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap.min.nr.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"

    - version: "2.2.1"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"

    - version: "2.2.0"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.0/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.0/js/bootstrap.min.js"

    - version: "2.1.1"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"

    - version: "2.1.0"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js"

    - version: "2.0.4"
      css_complete: "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.0.4/css/bootstrap-combined.min.css"
      javascript:   "//maxcdn.bootstrapcdn.com/twitter-bootstrap/2.0.4/js/bootstrap.min.js"

fontawesome:

    - version: "4.3.0"
      latest: true
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"

    - version: "4.2.0"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"

    - version: "4.1.0"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"

    - version: "4.0.3"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"

    - version: "4.0.2"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css"

    - version: "4.0.1"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.min.css"

    - version: "4.0.0"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.min.css"

    - version: "3.2.1"
      css_complete: "//maxcdn.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"


# vim: ft=yaml sw=4 sts=4 et:
